### ISSUE TITLE
LABFAZ' new repo config

### ISSUE THREAD

**Issue by guico3lho** [labfaz/turborepo#1]
# Summary

Create template to start new repo with updated stack.

[template repo](https://github.com/TMTecnologia/turborepo-tmtecnologia)

## ToDo

- [x] #3
- [x] #2
- [x] #4
- [x] #5

## Minor

- [x] #8
- [x] #6
- [x] #7

## Done

- [x] update README.md
- [x] client app with NextJS
- [x] module path aliases config (avoid ../../../module on import)
- [x] prisma
- [x] trpc
- [x] nextAuth
- [x] tailwind
- [x] react-hook-forms
